[package]
name = "dhall-mock"
version = "0.0.1"
authors = [
    "fteychene <francois.teychene@gmail.com>",
    "rlecomte <romain.lecomte@gmail.com>"
]
edition = "2018"

[dependencies]
serde = "1.0"
serde_dhall = "0.5"
